### ISSUE TITLE
As a PDS manager, I want to see the ingestion status in the registry

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/archive-analytics#29] opened 2023-02-28 19:55 UTC
## 💪 Motivation
...so that I can see the progresses of the ingestion, overall, and compare to what is available in the legacy registry

## ⚖️ Acceptance Criteria
**Given** the engineering node opensearch
**When I perform** going to the dashboards
**Then I expect** to see a dashboard showing the ingested bundles per discipline node
**Then I expect** to compare the ingestion counts and individuals ingested bundles with what is available in the legacy registry

## ⚙️ Engineering Details

Use kibana dashboards

**Comment by tloubrieu-jpl** [comment] 2023-02-28 20:00
Started, need to add legacy registry status, need to split series by node instead of discipline. Node need to be a keyword type instead of text

**Comment by jordanpadams** [comment] 2023-02-28 21:23
duplicate of NASA-PDS/registry#168

**Closed by jordanpadams** 2023-02-28 21:23 UTC
Labels: B13.1, requirement, p.should-have, sprint-backlog
